### ISSUE TITLE
Support for `require` with config parameter

### ISSUE THREAD

**Issue by rhpijnacker** [OpenNTF/dojo-webpack-plugin#140]
Hi Chuck,

In our tests we use the ```config``` parameter for the require function sometimes to load mocked modules.
E.g.
```
  require({ map: { '*': {
    'my/module/path': 'my/mocked/module/path'
  }}}, ['the/module/under/test', function etc(...) {...});
```
this is partly why we needed the ```undef``` function, to make sure the ```the/module/under/test``` is loaded freshly with the mocked modules.
Would it be feasible to implement something like this for the webpack plugin?

Thanks, Ronald

**Comment by chuckdumont** [comment]
In theory, it should be possible.  The challenge would be figuring out how to associate a customized Dojo loaderScope object with the modules being required plus all of those module's dependencies.

**Comment by chuckdumont** [comment]
Looking into this a bit more, it seems that require with config parameters cannot be supported by webpack.  The reason is that when require is called with a config object, the config changes are applied to the global config persistently. A build-time processor like webpack cannot know when such changes would be applied at run-time, and therefore, cannot know how to evaluate down-stream module dependencies at build-time because it doesn't know which config will be in effect when any given module is loaded.
