### ISSUE TITLE
Unable to resolve custom widgets with "/" in their namespace, only "." works.

### ISSUE THREAD

**Issue by wmakley** [OpenNTF/dojo-webpack-plugin#247]
Very simple issue I encountered with my custom widgets.

1. This works:
`<div data-dojo-type="myapp.CustomWidget"></div>`
2. This doesn't work:
`<div data-dojo-type="myapp/CustomWidget"></div>`

Dojo docs have said to use the second form for a while though. Even weirder, the dojo-webpack-loader is fine with the newer for built-in dijits, so this works:

`<div data-dojo-type="dijit/layout/TabContainer" style="width: 100%; height: 400px;">`

Made an easy test case: https://github.com/wmakley/dojo-webpack-plugin-sample

Seems to be some issue with the parser, but it's quite soupy for me to "parse". Even with this bug the experience of using this loader is 500% better than the "dojo build tool" so I will probably just replace all my widget references for now. Thank you for your hard work!

**Comment by chuckdumont** [comment]
A couple of alternative solutions:

* Change the value of the `data-dojo-type attribute` to `myapp.CustomWidget` (as you've discovered) or `js/myapp/CustomWidget`.
* Add a `myapp: 'js/myapp',` to the paths entry in the js/loaderConfig and change the dependency in bootstrap.js from `./myapp/CustomWidget` to `myapp/CustomWidget`.

When specifying widgets using the dot notation, the requested widgets are obtained from the widget registry.  When using the slash notation, they are obtained from the AMD loader.  The later has several advantages, including the ability to use the loader config to relocate widgets on disk without having to change the widgets themselves, or the modules that use them.

The reason that you're encountering problems has to do with inconsistency between the name used to address the widget in the markup (`myapp/CustomWidget`) and the way the widget is known to webpack (`js/myapp/CustomWidget`).  Because the module `js/bootstrap` is depending on `./myapp/CustomWidget`, webpack records the module id as `js/myapp/CustomWidget`.  This is the name that is used to resolve any references to the module at runtime (e.g. by the Dojo parser).  In order for runtime references to widgets to resolve correctly, the name needs to be the same as the resolved module id used at build time.  Either of the changes suggested above will do that.

**Comment by chuckdumont** [comment]
Another solution would be to define a loaderConfig alias as follows:
```javascript
aliases: [['myapp', 'js/myapp']],
```
This is probably the best solution since it does not require changes to any of the modules.

**Comment by wmakley** [comment]
Thanks, that explanation was clear and made complete sense to me. The only issue is my real life app that I was trying to fix actually has no prefix "js" directory, so I'm still not sure what the issue is. That said, AMD (webpack dependency tree) vs the registry gives me something to go on.

**Comment by wmakley** [comment]
I'm happy with your explanation and alias solution! Thank you again.
