### ISSUE TITLE
Project Compiles Twice

### ISSUE THREAD

**Issue by atdiff** [OpenNTF/dojo-webpack-plugin#251]
## Description

In projects that have dojo-webpack-plugin, the code gets compiled twice when ran with webpack-dev-server. First noticed with arcgis-webpack-plugin that uses dojo-webpack-plugin (https://github.com/Esri/arcgis-webpack-plugin/issues/54) under the covers but confirmed it occurs with just the use of dojo-webpack-plugin.
## Expected Behavior

The code should only compile once.
## Actual Behavior

Code is compiling twice (based on receiving two "Compiled successfully" messages) and in most cases a longer build/serve process.
## Possible Fix

When testing with [demo project](https://github.com/OpenNTF/dojo-webpack-plugin-sample), the dual compilation occurs. But with projects without the webpack plugins for arcgis or dojo, it doesn't happen.
## Steps to Reproduce

1. Use the code from https://github.com/OpenNTF/dojo-webpack-plugin-sample or https://github.com/Esri/jsapi-resources/tree/master/4.x/webpack/demo
2. npm install
3. npm run serve (for dojo project) or npm start (for arcgis project)
4. Note in the resulting output that there are two "Compiled successfully" messages

## Context

It's more of an annoyance than a big problem. Slows down the build. And when using bundle analysis and build notification plugins, it causes duplications of those tasks.
## Your Environment

* Version used: 4.11.0
* Browser Name and version: Chrome Version 75.0.3770.100 (64-bit)
* Operating System and version (desktop or mobile): Windows 10
* Link to your project if available: 
** https://github.com/OpenNTF/dojo-webpack-plugin-sample
** https://github.com/Esri/jsapi-resources/tree/master/4.x/webpack/demo

**Comment by chuckdumont** [comment]
Not really sure what's going on with this.  It has something to do with building the dojo loader because if you specify the loader option in your webpack config (see the [loader](https://github.com/OpenNTF/dojo-webpack-plugin#loader) option), then it only compiles once.

The double compile is only on startup of the dev server, but rebuilds only compile once.  If it really bothers you, then use a pre-built loader.  This isn't high on my list of things to look at, but thanks for opening the issue.

**Comment by chuckdumont** [comment]
More info on this.  The second compile is because dev-server is detecting that dojo.js has changed and is re-compiling the project, just as if any other source file changed.  

When not using the dojo-webpack-plugin loader option, the plugin builds the embedded loader using the dojo build tools as part of the webpack compilation.  So one of the source files used by webpack is built using non-webpack build tools during the compilation, and dev-server apparently sees the addition/modification of this file as a source file change which triggers the rebuild.

webpack-dev-server does not appear to have any options to tell it to ignore certain files, so I'm not sure that anything can be done about this other than using a pre-built loader as described in the previous comment.

**Comment by chuckdumont** [comment]
More info on this.  The second compile is because dev-server is detecting that dojo.js has changed and is re-compiling the project, just as if any other source file changed.  

When not using the dojo-webpack-plugin loader option, the plugin builds the embedded loader using the dojo build tools as part of the webpack compilation.  So one of the source files used by webpack is built using non-webpack build tools during the compilation, and dev-server apparently sees the addition/modification of this file as a source file change which triggers the rebuild.

webpack-dev-server does not appear to have any options to tell it to ignore certain files, so I'm not sure that anything can be done about this other than using a pre-built loader as described in the previous comment.

**Comment by chuckdumont** [comment]
Closing this because it's not really a bug and there is a workaround.

**Comment by atdiff** [comment]
@odoe is this workaround something that can be implemented in the arcgis-webpack-plugin? To help speed up build times a little
