### ISSUE TITLE
AMD source code using require instead of define are filtered out by filterAbsMids

### ISSUE THREAD

**Issue by ylavoie** [OpenNTF/dojo-webpack-plugin#280]
All modules in the entry array in webpack.config.js are removed if they use require instead of define.

Here is my webpack.config.js and a sample file which is removed. Changing the require for a define fixes the bug but I have many other files using require which need to stay as is.

[webpack.config.js.txt](https://github.com/OpenNTF/dojo-webpack-plugin/files/4400275/webpack.config.js.txt)
[Invoice.js.txt](https://github.com/OpenNTF/dojo-webpack-plugin/files/4400281/Invoice.js.txt)

**Comment by chuckdumont** [comment]
The example module you shared (Invoice.js) is not an AMD module.  Neither is it CommonJS.  See the [AMD specification](https://github.com/amdjs/amdjs-api/blob/master/AMD.md).

Frankly, I'm surprised that it even works with Dojo.  Perhaps Dojo can be more relaxed about the specification because it only supports one type of module.  Webpack support both AMD and CommonJS, so needs to be stricter about modules adhering to the module specification.

You mention fllterAbsMids in the title of this issue, but there are many more places in both dojo-webpack-plugin, and webpack itself, that expect AMD modules to identify themselves with a `define` function, so there is no simple fix for what you're trying to do.

**Comment by ylavoie** [comment]
Dojo might have been more relaxed than the spec. You are right, closing this issue.
