### ISSUE TITLE
Build error when dojo installed via npm

### ISSUE THREAD

**Issue by odoe** [OpenNTF/dojo-webpack-plugin#35]
Hi there,

First off, thanks for the plugin, looks awesome!

I was able to get the [sample app](https://github.com/OpenNTF/dojo-webpack-plugin-sample) to work perfectly when I installed dojo libs via Bower into a `libs` folder and used `npm run build --dojoRoot=libs`. No issue there, and I think I actually did a little dance.

However, if I npm install the dojo modules and use `npm run build --dojoRoot=node_modules` I get multiple errors in reference to `i18n` and `nls` files that look like this.

```
ERROR in ./node_modules/dojo/i18n.js!./node_modules/dijit/node_modules/dojo/nls/colors.js
Module build failed: ReferenceError: define is not defined
```

I'm not sure if there is another config option I need to adjust or not.

Thanks!

**Comment by chuckdumont** [comment]
There are a couple of issue here.  The first is the one you encountered with webpack loading dojo's i18n loader instead of dojo-webpack-plugin's i18n loader.  You can work around this by adding the following to your webpack.config.js:

```javascript
resolveLoader: {
  alias: {
    "dojo/i18n": path.resolve(__dirname, "node_modules", "dojo-webpack-plugin", "loaders", "dojo", "i18n")
  }
},
```

The second issue is the name of the dojo/util directory.  The node package is called `dojo-util`.  But Dojo's build machinery for building the loader expects the util directory to be located at `../util`.  I don't see a way of working around this since there is a node package called `util` already, so you can't use a symlink.  About all I can suggest is to [build the loader manually](https://github.com/OpenNTF/dojo-webpack-plugin#building-the-dojo-loader) using the Dojo installed in `lib` and then specifying the location of the built loader using the [loader](https://github.com/OpenNTF/dojo-webpack-plugin#loader) config option when you build your app with the Dojo in node_modules. 
```

**Comment by odoe** [comment]
Thanks for the response! That got me half-way there, I'm trying to see if I can figure out how to remap the `util`.

I got this trick from Sitepen a while ago when doing builds when Dojo was installed via NPM.

```
dojoConfig = {
  baseUrl: './node_modules/',
  packages: [
    {
      name: 'dojo',
      location: 'dojo'
    },
    {
      name: 'build',
      location: 'dojo-util/build'
    }
  ]
};
require('./node_modules/dojo/dojo.js');
```

Then use it like `$ node dojoconfig.js load=build --profile build-profile.js --release`. Currently working my way through plugin codebase to find how that custom config can be provided. If I can crack that nut, I'll make a PR.

Thanks!

**Comment by chuckdumont** [comment]
I tried adding the package override for `util` to `build-profile.js`.  Unfortunately, that didn't do the trick, because it isn't used when dojo.js is loaded by node.  If you could figure out how to pass config overrides via `global.dojoConfig`, that might work, but I'm not sure how how you pass globals when forking a node process.

**Comment by chuckdumont** [comment]
Should be fixed now by #36.  You can remove the `resolveLoader.alias` config as well.  Try it out using `2.0.12-rc1`.

**Comment by odoe** [comment]
That seems to work! Awesome, much appreciated!

I was getting pretty close with my local branch, but nowhere near as clean as your solution! Thanks!

**Comment by chuckdumont** [comment]
OK.  Version 2.0.12 has been published.  I also updated the sample app to use Dojo from npm so you no longer need to specify the location of Dojo when building.
